language: java
sudo: false
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
script:
  - ./gradlew test build
  - ./gradlew check jacocoTestReport --info
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)

